### PR TITLE
feat: user should be able to reset password

### LINKED ISSUE #18: [FEATURE] User should be able to reset password if he/she forgot his/her password
**Is your feature request related to a problem? Please describe.**
- In a case where a user forgot his/her password he will need to be able to reset it.

**Describe the solution you'd like**
- Create Rest API functionalities for a user to be able to reset his/her password

**Describe alternatives you've considered**
- None

**Additional context**
- None

### PR DESCRIPTION
**Pull request by oyewoas**
## Description
- Created validator for  forgot and reset password,
- Created fotgot and reset password method in the auth controller
- Created password reset model
- Wrote unit test for validators, controllers and model

Delivers #18

## How Has This Been Tested?
1. In your terminal, run `git clone https://github.com/BuildForSDG/SmeVest-Backend.git`
2. Run `cd SmeVest-Backend`
3. Run `git fetch origin ft-reset-password`
4. Run `git checkout origin/ft-reset-password`
5. Run `yarn install`
6. create a `.env` file in the root directory then add details as seen in `.env-example` file
7. Run `yarn run test` to run unit tests
8. Run `yarn run start:dev` to start the development server
9. To test forgot password functionality with postman use `http://localhost:4000/api/v1/auth/passwords/forgot` with appropriate parameters,

- Sample request:
```json
{
	"email": "emails@mail.com",
}
```

- Sample success response :
 ```json
{
    "status": 200,
    "message": "Forgot password email sent"
}
```

10. To test reset password functionality with postman use `http://localhost:4000/api/v1/auth/passwords/reset` with appropriate parameters,

- Sample request:
```json
{
	"password": "password",
	"email": "emails@mail.com",
	"token": "titJJyrs2fJgRC1pOZ79hCV5E99L2wN6"
}
```

- Sample success response :
 ```json
{
    "status": 200,
    "message": "Password has been reset"
}
```
**NOTE**: Try to use a valid email

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Johnny2020Ade — COMMENTED** [review]
It's nice progress.

**Review by Johnny2020Ade — DISMISSED** [review]

**Review by Yasholma — CHANGES_REQUESTED** [review]
There is a password characters error of some sort. Did u change the validation rule for the password?

**Comment by oyewoas** [comment]
> There is a password characters error of some sort. Did u change the validation rule for the password?

@Yasholma  I did not change the validation rule of the password what has been there all the while is min of 6 characters and Maximum of 10 characters

> There is a password characters error of some sort. Did u change the validation rule for the password?

@Yasholma I did not change the password validation rule, what has been there all the while is min 6 and max 10 characters

**Review by Yasholma — DISMISSED** [review]
Nice and Cool. Implemented

**Review by Yasholma — APPROVED** [review]

**Review by Johnny2020Ade — APPROVED** [review]

**Pull request merged**
